# Глава 2. Предобработка исследовательских данных

## 1. Подключение и работа с библиотекой numpy

### 1.1

In [4]:
import numpy as np

a=np.array([[2.3, 5.1, 4.7],
            [3.5, 6.7, 1.5],
            [8.4, 3.1, 9.2]])

b=np.array([[4.3, 8.1, 0.1],
            [3.7, 6.2, 1.5],
            [2.4, 5.7, 4.7]])


1)

In [5]:
string,column=a.shape
string_1,column_1=b.shape
cos_a=np.cos(a)
sin_b=np.sin(b)

print("Массив а содержит", string, "строк и", column, "столбцов.")
print("Массив b содержит", string_1, "строк и", column_1, "столбцов.", end="\n"*2)

Массив а содержит 3 строк и 3 столбцов.
Массив b содержит 3 строк и 3 столбцов.



2)

In [6]:
print(a+b, end="\n"*2)
print(a-b, end="\n"*2)
print(a*b, end="\n"*2)
print(a/b, end="\n"*2)

[[ 6.6 13.2  4.8]
 [ 7.2 12.9  3. ]
 [10.8  8.8 13.9]]

[[-2.  -3.   4.6]
 [-0.2  0.5  0. ]
 [ 6.  -2.6  4.5]]

[[ 9.89 41.31  0.47]
 [12.95 41.54  2.25]
 [20.16 17.67 43.24]]

[[ 0.53488372  0.62962963 47.        ]
 [ 0.94594595  1.08064516  1.        ]
 [ 3.5         0.54385965  1.95744681]]



3)

In [29]:
print(pow(a,2),end="\n"*2)

[ 1.44  5.76  9.   12.25 44.89  2.25 70.56  9.61 84.64]



4)

In [20]:
print(b/2,end="\n"*2)

[[2.15 4.05 0.05]
 [1.85 3.1  0.75]
 [1.2  2.85 2.35]]



5)

In [40]:
print("cos a:", cos_a,end="\n"*2)
print("sin b:", sin_b,end="\n"*2)
print(cos_a+sin_b)

cos a: [[-0.66627602  0.37797774 -0.01238866]
 [-0.93645669  0.91438315  0.0707372 ]
 [-0.51928865 -0.99913515 -0.97484362]]

sin b: [[-0.91616594  0.96988981  0.09983342]
 [-0.52983614 -0.0830894   0.99749499]
 [ 0.67546318 -0.55068554 -0.99992326]]

[[-1.58244196  1.34786755  0.08744475]
 [-1.46629283  0.83129375  1.06823219]
 [ 0.15617453 -1.54982069 -1.97476688]]


### 1.2


In [51]:
import numpy as np

aq = np.array([1.2, 2.4, 3.0, 3.5, 6.7, 1.5, 8.4, 3.1, 9.2])

1) 

In [52]:
print(a.shape,end="\n"*2)

(9,)



2)

In [53]:
arr_1=a.reshape((9, 1))
print(arr_1,end="\n"*2)

[[1.2]
 [2.4]
 [3. ]
 [3.5]
 [6.7]
 [1.5]
 [8.4]
 [3.1]
 [9.2]]



3)

In [54]:
arr_2=a.reshape((3, 3))
print(arr_2,end="\n"*2)

[[1.2 2.4 3. ]
 [3.5 6.7 1.5]
 [8.4 3.1 9.2]]



4)

In [55]:
print(arr_2.max(axis=0),end="\n"*2)
print(arr_2.max(axis=1),end="\n"*2)

[8.4 6.7 9.2]

[3.  6.7 9.2]



5)

In [56]:
print(arr_2.max(axis=0),end="\n"*2)
print(arr_2.max(axis=1),end="\n"*2)

[8.4 6.7 9.2]

[3.  6.7 9.2]



6)

In [57]:
print(arr_2.sum(axis=0),end="\n"*2)
print(arr_2.sum(axis=1),end="\n"*2)

[13.1 12.2 13.7]

[ 6.6 11.7 20.7]

