# Глава 2. Предобработка исследовательских данных

## 1. Подключение и работа с библиотекой numpy

### 1.1

In [2]:
import numpy as np

a=np.array([[2.3, 5.1, 4.7],
            [3.5, 6.7, 1.5],
            [8.4, 3.1, 9.2]])

b=np.array([[4.3, 8.1, 0.1],
            [3.7, 6.2, 1.5],
            [2.4, 5.7, 4.7]])


1)

In [3]:
string,column=a.shape
string_1,column_1=b.shape
cos_a=np.cos(a)
sin_b=np.sin(b)

print("Массив а содержит", string, "строк и", column, "столбцов.")
print("Массив b содержит", string_1, "строк и", column_1, "столбцов.", end="\n"*2)

Массив а содержит 3 строк и 3 столбцов.
Массив b содержит 3 строк и 3 столбцов.



2)

In [4]:
print(a+b, end="\n"*2)
print(a-b, end="\n"*2)
print(a*b, end="\n"*2)
print(a/b, end="\n"*2)

[[ 6.6 13.2  4.8]
 [ 7.2 12.9  3. ]
 [10.8  8.8 13.9]]

[[-2.  -3.   4.6]
 [-0.2  0.5  0. ]
 [ 6.  -2.6  4.5]]

[[ 9.89 41.31  0.47]
 [12.95 41.54  2.25]
 [20.16 17.67 43.24]]

[[ 0.53488372  0.62962963 47.        ]
 [ 0.94594595  1.08064516  1.        ]
 [ 3.5         0.54385965  1.95744681]]



3)

In [5]:
print(pow(a,2),end="\n"*2)

[[ 5.29 26.01 22.09]
 [12.25 44.89  2.25]
 [70.56  9.61 84.64]]



4)

In [6]:
print(b/2,end="\n"*2)

[[2.15 4.05 0.05]
 [1.85 3.1  0.75]
 [1.2  2.85 2.35]]



5)

In [7]:
print("cos a:", cos_a,end="\n"*2)
print("sin b:", sin_b,end="\n"*2)
print(cos_a+sin_b)

cos a: [[-0.66627602  0.37797774 -0.01238866]
 [-0.93645669  0.91438315  0.0707372 ]
 [-0.51928865 -0.99913515 -0.97484362]]

sin b: [[-0.91616594  0.96988981  0.09983342]
 [-0.52983614 -0.0830894   0.99749499]
 [ 0.67546318 -0.55068554 -0.99992326]]

[[-1.58244196  1.34786755  0.08744475]
 [-1.46629283  0.83129375  1.06823219]
 [ 0.15617453 -1.54982069 -1.97476688]]


### 1.2


In [8]:
import numpy as np

aq = np.array([1.2, 2.4, 3.0, 3.5, 6.7, 1.5, 8.4, 3.1, 9.2])

1) 

In [9]:
print(a.shape,end="\n"*2)

(3, 3)



2)

In [10]:
arr_1=a.reshape((9, 1))
print(arr_1,end="\n"*2)

[[2.3]
 [5.1]
 [4.7]
 [3.5]
 [6.7]
 [1.5]
 [8.4]
 [3.1]
 [9.2]]



3)

In [11]:
arr_2=a.reshape((3, 3))
print(arr_2,end="\n"*2)

[[2.3 5.1 4.7]
 [3.5 6.7 1.5]
 [8.4 3.1 9.2]]



4)

In [12]:
print(arr_2.max(axis=0),end="\n"*2)
print(arr_2.max(axis=1),end="\n"*2)

[8.4 6.7 9.2]

[5.1 6.7 9.2]



5)

In [13]:
print(arr_2.max(axis=0),end="\n"*2)
print(arr_2.max(axis=1),end="\n"*2)

[8.4 6.7 9.2]

[5.1 6.7 9.2]



6)

In [14]:
print(arr_2.sum(axis=0),end="\n"*2)
print(arr_2.sum(axis=1),end="\n"*2)

[14.2 14.9 15.4]

[12.1 11.7 20.7]



### 1.3

In [15]:
a = np.array([[4, 2], [9, 1]])
b = np.array([[5, 3], [2, 5]])

1)

In [16]:
new_array_1 = np.vstack((a, b))
print(new_array_1)

[[4 2]
 [9 1]
 [5 3]
 [2 5]]


2)

In [17]:
array_2 = new_array_1[:,0][0:3]
print(array_2)

[4 9 5]


3)

In [18]:
print(array_2.sum())
print(array_2.min())
print(array_2.max())

18
4
9


4)

In [19]:
new_array_2 = np.hstack((a, b))
print(new_array_2)

[[4 2 5 3]
 [9 1 2 5]]


5)

In [20]:
print(new_array_2[0,:][0:3])

[4 2 5]


6)

In [21]:
print(sum(new_array_2[0,:][0:3]))
print(max(new_array_2[0,:][0:3]))
print(min(new_array_2[0,:][0:3]))

11
5
2


### 1.4

In [22]:
from numpy import linalg as lg

a = np.array([[5, 4],[2, -6]])
b = np.array([14, -2])
decide =lg.solve(a,b)
print(decide)

[2. 1.]


### 1.5

In [23]:
from numpy import linalg as lg

a = np.array([[2, 8],
              [1, -6]])

b = np.array([[3, 2, 7],
             [4, 1, 8],
             [6, 3, 7]])

c = np.array([[4, 3, 2, 7],
             [6, 1, 1, -2],
             [7, 5, 8, 1],
             [9, 5, -3, -5]])

1)

In [24]:
print(a.transpose(),end="\n"*2)
print(b.transpose(),end="\n"*2)
print(c.transpose(),end="\n"*2)

[[ 2  1]
 [ 8 -6]]

[[3 4 6]
 [2 1 3]
 [7 8 7]]

[[ 4  6  7  9]
 [ 3  1  5  5]
 [ 2  1  8 -3]
 [ 7 -2  1 -5]]



2)

In [25]:
print(lg.inv(a),end="\n"*2)
print(lg.inv(b),end="\n"*2)
print(lg.inv(c),end="\n"*2)

[[ 0.3   0.4 ]
 [ 0.05 -0.1 ]]

[[-0.5483871   0.22580645  0.29032258]
 [ 0.64516129 -0.67741935  0.12903226]
 [ 0.19354839  0.09677419 -0.16129032]]

[[ 0.05464191  0.23129973 -0.05251989 -0.0265252 ]
 [-0.00424403 -0.37718833  0.11087533  0.16710875]
 [-0.06153846  0.03076923  0.10769231 -0.07692308]
 [ 0.13103448  0.02068966 -0.04827586 -0.03448276]]



3)

In [26]:
print(lg.det(a),end="\n"*2)
print(lg.det(b),end="\n"*2)
print(lg.det(c),end="\n"*2)

-20.000000000000007

31.0

1885.0000000000005



4)

In [27]:
axis0 = np.split(b, 3, axis=0)
print(lg.norm(axis0),end="\n"*2)

15.394804318340652



5)

In [28]:
axis1 = np.split(c, 4, axis=1)
print(lg.norm(axis1),end="\n"*2)

19.974984355438178



1.6

In [29]:
import random

a = np.array([random.randint(0, 100) for i in range(0, 100, 1)])
print(a)

count = 0
for i in a:
     if i>50:
        count+=1
print (count)

count_new = 0
count_new = sum(map(lambda item: item > 50, a))
print(count_new)

[ 75  68  13  42  16  18  98  21  70   3  32  18  10  36  86  42  91  21
 100  57  77  81  50   2  54  34  11  29  65  42  15  83  64  10  35  39
  50  29  36  92  24  83  60  95  98  71  96  28  38  80  16  65  55  49
  99   6  18  44  10   8  62  51  23   3  30  37  49  51  33  56  80  93
  53   3  80  18  13   2  62  76  59  19  37  58  21  45  74  57  63  63
  33  64  72  91   2 100  87  74  39  90]
48
48
